services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./app:/var/www/html
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - app-network
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      # - ./app:/var/www/html
      - ./data:/var/www/html/data
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_GROUP_CHAT_ID: ${TELEGRAM_GROUP_CHAT_ID}
      TELEGRAM_GROUP_ADMIN: ${TELEGRAM_GROUP_ADMIN}
      TRELLO_API_KEY: ${TRELLO_API_KEY}
      TRELLO_API_TOKEN: ${TRELLO_API_TOKEN}
      TRELLO_BOARD_ID: ${TRELLO_BOARD_ID}
      TRELLO_IN_PROGRESS_LIST_ID: ${TRELLO_IN_PROGRESS_LIST_ID}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge